from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
if False:
    from typing import Dict, List, Tuple, Union, Optional

def convertText(text): ...
def canMegerBefore(ch): ...
def getConvertType(ch): ...
def filterAndCorrectArabic(hexText): ...
def isLamChar(a): ...
def isSpaceChar(a): ...
def inMergeRange(ch): ...
def convertCharacters(chars): ...
def convertLamAlef(ch, offset): ...
def convertChar(ch, offset): ...
def HexToUni(hexStr): ...
def isAlefChar(a): ...
def canMergeAfter(ch): ...
def ByteToHex(byteStr): ...
def isArabic(ch): ...


MERGE_MAP : list
MERGE_TYPE : list
t_start : int
t_end : int
t_middle : int
t_none : int

