from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
import maya.api.OpenMayaRender as omr


if False:
    from typing import Dict, List, Tuple, Union, Optional

def mayaIsVP2Capable(): ...
def mayaVP2API(): ...
def mayaVP2APIIsOpenGLCoreProfile(): ...
def mayaVP2APIIsDirectX11(): ...
def mayaVP2APIIsOpenGL(): ...

