from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
if False:
    from typing import Dict, List, Tuple, Union, Optional

class EnterLightScope:
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...
    def __init__(self, model): ...


class EnterMayaScope:
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...
    def __init__(self, model): ...



