if (NOT PYTHON_CONFIG_SUFFIX)
    message(STATUS "PySide2Config: Using default python: -python2.7")
    SET(PYTHON_CONFIG_SUFFIX -python2.7)
endif()
include(${CMAKE_CURRENT_LIST_DIR}/PySide2Config${PYTHON_CONFIG_SUFFIX}.cmake)
