from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
if False:
    from typing import Dict, List, Tuple, Union, Optional

def createdByPython(*args, **kwargs): ...
def invalidate(*args, **kwargs): ...
def delete(*args, **kwargs): ...
def isValid(*args, **kwargs): ...
def ownedByPython(*args, **kwargs): ...
def getCppPointer(*args, **kwargs): ...
def wrapInstance(*args, **kwargs): ...
def dump(*args, **kwargs): ...
def getAllValidWrappers(*args, **kwargs): ...


__version__ : str

