from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
import maya.mel as mel
import maya.cmds as cmds
import platform


if False:
    from typing import Dict, List, Tuple, Union, Optional

def addUVNodeToSVG(svgTransform, svgExtruder): ...
def connectSVGAdjustDeformer(svgMesh, svgTransform, svgExtruder, svgTool): ...
def addPolyRemeshNodeType(svgTransform, svgExtruder, svgTool, svgMesh, svgAdjuster): ...
def createSVGTool(fromPaste='False', fromImport='False'): ...
def svgScriptJobSetup(svgTool): ...
def setUpSVGNetwork(fromPaste='False', fromImport='False', legacy='False', filePath='None'): ...
def showThesvgTool(svgTool, svgTransform): ...
def setUpSVGNetworkWithNode(svgTool, fromPaste='False', fromImport='False', legacy='False', filePath='None'): ...
def connectSVGShellDeformer(svgMesh, svgTransform, svgExtruder, svgTool, svgAdjuster): ...

