if (NOT PYTHON_CONFIG_SUFFIX)
    message(STATUS "Shiboken2Config: Using default python: .cp39-win_amd64")
    SET(PYTHON_CONFIG_SUFFIX .cp39-win_amd64)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/Shiboken2Config${PYTHON_CONFIG_SUFFIX}.cmake")
