from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
from . import QtCore


from PySide2.QtWidgets import QWidget as _QWidget


if False:
    from typing import Dict, List, Tuple, Union, Optional

class QQuickWidget(_QWidget):
    def __init__(*args, **kwargs):
        """
        x.__init__(...) initializes x; see help(type(x)) for signature
        """
        ...
    def dragEnterEvent(*args, **kwargs): ...
    def dragLeaveEvent(*args, **kwargs): ...
    def dragMoveEvent(*args, **kwargs): ...
    def dropEvent(*args, **kwargs): ...
    def engine(*args, **kwargs): ...
    def errors(*args, **kwargs): ...
    def event(*args, **kwargs): ...
    def focusInEvent(*args, **kwargs): ...
    def focusOutEvent(*args, **kwargs): ...
    def format(*args, **kwargs): ...
    def grabFramebuffer(*args, **kwargs): ...
    def hideEvent(*args, **kwargs): ...
    def initialSize(*args, **kwargs): ...
    def keyPressEvent(*args, **kwargs): ...
    def keyReleaseEvent(*args, **kwargs): ...
    def mouseDoubleClickEvent(*args, **kwargs): ...
    def mouseMoveEvent(*args, **kwargs): ...
    def mousePressEvent(*args, **kwargs): ...
    def mouseReleaseEvent(*args, **kwargs): ...
    def quickWindow(*args, **kwargs): ...
    def resizeEvent(*args, **kwargs): ...
    def resizeMode(*args, **kwargs): ...
    def rootContext(*args, **kwargs): ...
    def rootObject(*args, **kwargs): ...
    def setClearColor(*args, **kwargs): ...
    def setContent(*args, **kwargs): ...
    def setFormat(*args, **kwargs): ...
    def setResizeMode(*args, **kwargs): ...
    def setSource(*args, **kwargs): ...
    def showEvent(*args, **kwargs): ...
    def sizeHint(*args, **kwargs): ...
    def source(*args, **kwargs): ...
    def status(*args, **kwargs): ...
    def timerEvent(*args, **kwargs): ...
    def wheelEvent(*args, **kwargs): ...
    Error : Status
    
    Loading : Status
    
    Null : Status
    
    Ready : Status
    
    ResizeMode : Type[ResizeMode]
    
    SizeRootObjectToView : ResizeMode
    
    SizeViewToRootObject : ResizeMode
    
    Status : Type[Status]
    
    __new__ : builtin_function_or_method
    
    sceneGraphError : PySide2.QtCore.Signal
    
    staticMetaObject : PySide2.QtCore.QMetaObject
    
    statusChanged : PySide2.QtCore.Signal



