from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
import maya.cmds as cmds


if False:
    from typing import Dict, List, Tuple, Union, Optional

def attrType(nodeType, attribute): ...
def niceName(nodeType, attribute): ...
def registerNiceNames(namesMap): ...
def checkNiceNames(namesMap): ...

