from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
import maya.mel as mel
from . import singleton


if False:
    from typing import Dict, List, Tuple, Union, Optional

def loadTemplate(nodeType, nodeName): ...
def registerInstance(obj): ...
def onCreate(key): ...
def getAEEventFuncs(): ...
def onReplace(key): ...
def wrapAETemplate(nodeType): ...
def deregisterInstance(obj): ...
def registerMelProcWithStringArg(procName, funcName): ...

